import XCTest
@testable import SQLCore

final class StatementWriteGuardTests: XCTestCase {
    func testAllowsReads() {
        XCTAssertFalse(StatementWriteGuard.isWrite("SELECT 1", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("  -- note\nSELECT * FROM t", kind: .mysql))
        XCTAssertFalse(StatementWriteGuard.isWrite("EXPLAIN SELECT 1", kind: .sqlite))
        XCTAssertFalse(StatementWriteGuard.isWrite("GET foo", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("SCAN 0", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("HGETALL user:1", kind: .redis))
    }

    func testBlocksSQLWrites() {
        XCTAssertTrue(StatementWriteGuard.isWrite("DELETE FROM t", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("INSERT INTO t VALUES (1)", kind: .mysql))
        XCTAssertTrue(StatementWriteGuard.isWrite("UPDATE t SET a = 1", kind: .sqlite))
        XCTAssertTrue(StatementWriteGuard.isWrite("CREATE TABLE t (id int)", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("WITH x AS (SELECT 1) DELETE FROM t", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("SELECT 1; DROP TABLE t", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("DROP TABLE t", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("EXPLAIN ANALYZE DELETE FROM t", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("EXPLAIN DELETE FROM t", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("EXPLAIN ANALYZE SELECT * FROM t", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("SELECT * FROM t WHERE note = 'drop it'", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("SELECT comment FROM comments", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("SELECT * INTO archive FROM t", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("SELECT * INTO OUTFILE '/tmp/export' FROM t", kind: .mysql))
        XCTAssertTrue(StatementWriteGuard.isWrite("RENAME TABLE old_name TO new_name", kind: .mysql))
        XCTAssertTrue(StatementWriteGuard.isWrite("SET GLOBAL read_only = 1", kind: .mysql))
        XCTAssertTrue(StatementWriteGuard.isWrite("SET default_transaction_read_only = off", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("SET transaction_read_only = 'off'", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("BEGIN WORK READ WRITE", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("START TRANSACTION READ WRITE", kind: .postgres))
        XCTAssertTrue(StatementWriteGuard.isWrite("SET DEFAULT ROLE ALL TO someone", kind: .mysql))
        XCTAssertFalse(StatementWriteGuard.isWrite("SET default_transaction_read_only = on", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("SET ROLE viewer", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("BEGIN", kind: .postgres))
        XCTAssertFalse(StatementWriteGuard.isWrite("SELECT * INTO @value FROM t", kind: .mysql))
    }

    func testBlocksRedisWrites() {
        XCTAssertTrue(StatementWriteGuard.isWrite("SET foo bar", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("DEL foo", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("HSET user:1 name ada", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("INCR counter", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("EVAL return 1 0", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("XADD stream * value 1", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("SORT source STORE destination", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("PSETEX key 100 value", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("LINSERT mylist BEFORE pivot value", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("ZMPOP 1 zset MIN", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("ZRANGESTORE dst src 0 -1", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("GETEX key EX 10", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("CONFIG SET maxmemory 100mb", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("CLUSTER ADDSLOTS 1", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("CLIENT KILL id 5", kind: .redis))
        XCTAssertTrue(StatementWriteGuard.isWrite("FUNCTION DELETE mylib", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("CONFIG GET maxmemory", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("SLOWLOG GET 10", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("LATENCY HISTORY event", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("ACL WHOAMI", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("SCRIPT EXISTS abc", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("FUNCTION LIST", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("EVAL_RO \"return 1\" 0", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("FCALL_RO f 0 key", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("GETEX key", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("CLUSTER INFO", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("CLIENT INFO", kind: .redis))
        XCTAssertFalse(StatementWriteGuard.isWrite("# comment\nGET foo", kind: .redis))
    }
}
